function [xh, Px] = kf(state, Pstate, pNoise, oNoise, obs, U1, U2, model)

% KF  Kalman Filter
%   This filter assumes the following standard state-space model:
%
%     x(k) = ffun[x(k-1),v(k-1),U1(k-1)]
%     y(k) = hfun[x(k),n(k),U2(k)]
%
%   where x is the system state, v the process noise, n the observation noise, u1 the exogenous input to the state
%   transition function, u2 the exogenous input to the state observation function and y the noisy observation of the
%   system.
%
%   INPUT
%         state                state mean at time k-1          ( xh(k-1) )
%         Pstate               state covariance at time k-1    ( Px(k-1) )
%         pNoise               process noise data structure     (usually 'gaussian')
%         oNoise               observation noise data structure (usually 'gaussian')
%         obs                  noisy observations starting at time k ( y(k),y(k+1),...,y(k+N-1) )
%         U1                   exogenous input to state transition function starting at time k-1 ( u1(k-1),u1(k),...,u1(k+N-2) )
%         U2                   exogenous input to state observation function starting at time k  ( u2(k),u2(k+1),...,u2(k+N-1) )
%         model          inference data structure generated by GENINFDS function.
%
%   OUTPUT
%         xh                   estimates of state starting at time k ( E[x(t)|y(1),y(2),...,y(t)] for t=k,k+1,...,k+N-1 )
%         Px                   state covariance
%=============================================================================================


Xdim  = size(state,1);                                    % state dimension
Odim  = size(obs,1);                                      % observation dimension

Vdim  = model.Vdim;                                        % process noise dimension
Ndim  = model.Ndim;                                        % observation noise dimension

NOV = size(obs,2);                                               % number of input vectors


%------------------------------------------------------------------------------------------------------------------

% Initializations
xh   = zeros(Xdim,NOV);
xh_  = zeros(Xdim,NOV);
yh_  = zeros(Odim,NOV);
inov = zeros(Odim,NOV);

if (model.U1dim==0), UU1 = []; end
if (model.U2dim==0), UU2 = []; end


%--------------------------------------- Loop over all input vectors --------------------------------------------
for i=1:NOV,

    if (model.U1dim) UU1 = U1(:,i); end           % get exogenous input
    if (model.U2dim) UU2 = U2(:,i); end           % get exogenous input

    %------------------------------------------------------
    %--- PREDICTION STEP

    A = model.A;
    G = model.G;

    xh_(:,i) = model.ffun( model, state, pNoise.mu, UU1);

    Px_      = A*Pstate*A' + G*pNoise.cov*G';

    %--- UPDATE STEP
    C = model.C;
    H = model.H;

    Py        = C*Px_*C' + H*oNoise.cov*H';
    KG        = Px_ * C'/Py;

    yh_(:,i)  = model.hfun( model, xh_(:,i), oNoise.mu, UU2);

    inov(:,i) = obs(:,i) - yh_(:,i);

    xh(:,i)   = xh_(:,i) + KG * inov(:,i);
    Px        = Px_ - KG*Py*KG';

  
    state  = xh(:,i);
    Pstate = Px;



end   %--- for loop


end


